services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./types:/opt/app/types
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
    ports:
      - '9229:9229'
    command: ["npm", "run", "develop"]

  strapiDB:
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - strapi-data-development:/var/lib/postgresql/data/

  strapiAdminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=strapiDB
    depends_on:
      - strapiDB
    networks:
      - strapi-network

volumes:
  strapi-data-development:
